### ISSUE TITLE
Runtime.UnhandledPromiseRejection: Error: Property type \"undefined\" not valid for Swagger definitions

### ISSUE THREAD

**Issue by SunaoSuzu** [pharindoko/json-serverless#360] opened 2020-05-09 13:54 UTC
Hi

Could you help me? 

I have deployed json-serverless and worked well in these days. But a few hours ago ,
suddenly error was happened and the situation is not recovered.
(With same db.json json-server works well at my local  )

**Describe the bug**
2020-05-09T13:46:22.069Z	f06f8de4-f3a8-4f67-b940-79a385076cdf	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Property type \"undefined\" not valid for Swagger definitions",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Property type \"undefined\" not valid for Swagger definitions",
        "stack": [
            "Error: Property type \"undefined\" not valid for Swagger definitions",
            "    at SwaggerDefGen.conversorSelection (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:179:19)",
            "    at SwaggerDefGen.convertArray (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:115:14)",
            "    at SwaggerDefGen.conversorSelection (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:163:18)",
            "    at /var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:140:19",
            "    at Array.forEach (<anonymous>)",
            "    at SwaggerDefGen.convertObject (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:137:26)",
            "    at SwaggerDefGen.conversorSelection (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:167:18)",
            "    at SwaggerDefGen.convertArray (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:115:14)",
            "    at SwaggerDefGen.conversorSelection (/var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:163:18)",
            "    at /var/task/node_modules/json-serverless-lib/lib/specifications/swagger/swagger.defgen.js:20:23"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Property type \"undefined\" not valid for Swagger definitions",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:310:20)",
        "    at process.EventEmitter.emit (domain.js:482:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}

**To Reproduce**
Everytime same error is happend.
I tried both from my app and browser and curl command.

Please help.

**Comment by pharindoko** [comment] 2020-05-09 23:07
Hey, can you provide the json file ?
Please post it here or you can as well send it privately. ... florian.fuss@freenet.de

Other options:

Verify you have the latest version via 
npm i -g json serverless
And/or
Try to deploy just the demo db.json mentioned in the readme ...

br, 

Flo

**Comment by SunaoSuzu** [comment] 2020-05-10 01:02
Here is Json file

I have re-installed json-server-less now with using same file I attached here.
But situation is not recovered ...

**Comment by SunaoSuzu** [comment] 2020-05-10 01:03
Oh sorry..

Here is json

[db.json.zip](https://github.com/pharindoko/json-serverless/files/4604967/db.json.zip)

**Comment by pharindoko** [comment] 2020-05-10 07:17
Thansk @SunaoSuzu,

I had a look to it. And even tried it with an earlier version 1.5.33. No chance.
The error is:
```
Error: Property type "undefined" not valid for Swagger definitions
```
https://github.com/pharindoko/json-serverless/blob/c4011fd1291ebd7aee97c0de4addf8fce8436c3b/packages/server/src/specifications/swagger/swagger.defgen.ts#L158


1. The issue is this property - 
  "environments": []

2. Why this error appears:
Empty Arrays are not allowed. Swagger wants to have the type of the array

```
  environment:
    type: array
    items:
      type: **object, string, bool, number ...**
    title: comments
```

json-serverless generates the spec on the fly. It takes the first element and tries to identify the different properties and assign it to types / swagger definitions.

At that moment it cannot know what the type inside the empty array should be.
And this is why it fails.
Type in a number e.g. and your goog to go.
 "environments": [1, 2],"


**3. Solution Proposal:**

short-term solution: 
- Delete "environments": [] out of each item and your good to go.
- Validation: I will embed an additional validation on the start to avoid that more people run into this issue.

mid-term solution: (please don`t wait for this, will take a few weeks ...)
- Maybe an optional json-schema could help to solve this.
- Maybe to add an option in the appconfig where you can additionally describe the type of a property in dot notation to influence the types at the generation.
Need time to think about it and do some checks....

br,

Flo

**Comment by SunaoSuzu** [comment] 2020-05-10 10:31
@pharindoko 

Thank you so much!!
I did Delete "environments": [] out of each item and your good to go.
The situation was recovered!!!

But we need empty array. So I wanna do Disable Swagger UI Option. We don't need swagger and graphql. Could you let me know how to do it or the document I have to look.

Thanks!

**Comment by pharindoko** [comment] 2020-05-10 12:46
Hey,

it was part of the appconfig and needs to be added as cli flag and part of the core.app.
I will do this the next few days.

The swagger addition should not break the json-server functionality that‘s clear.
So addi g this disable function makes sense...

**Comment by SunaoSuzu** [comment] 2020-05-11 00:38
Thank you so much!!
I will wait!

**Comment by pharindoko** [comment] 2020-05-12 20:08
Hey @SunaoSuzu,

I have release a new version: 

Following commands you can use now. Be aware that you always have to attach the flag at the current moment:

```
jsonsls run xxx.json --no-swagger
jsonsls create-stack xxx.json --no-swagger
jsonsls update-stack --no-swagger
```
More information:
https://github.com/pharindoko/json-serverless/tree/master/packages/cli

**Closed** 2020-05-13 15:03 UTC
Labels: bug
